version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
  db:
    image: postgres:16.9-bullseye
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      #- ./Init Database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  postgres-data: